export const SPHERE_RADIUS = 5
export const SURFACE = SPHERE_RADIUS + 0.06
export const CELL_COUNT = 225
export const MAX_CELLS = 500
export const FOOD_COUNT = 26000
export const GRID = 0.35
export const SPRING = 22
export const FIXED_DT = 1 / 60
export const MAX_STEPS = 40

export const MIN_RADIUS = 0.07
export const MAX_RADIUS = 0.26
export const START_RADIUS = 0.09
export const GROWTH_PER_FOOD = 0.0005
export const ABSORB_CAP = 3
export const MITO_TIME = 18
export const MITO_HOLD = 0.2
export const MITO_FADE = 0.4
export const MITO_NEAR = 2.1
export const MITO_SEP = 2.8

export const WIDTH = 0.06
export const TAIL_SEGMENTS = 24
export const TAIL_LEN = 0.30
export const TAIL_AMP = 0.1
export const TAIL_FREQ = 24.0
export const TAIL_WAVE = 24.0
export const THRUST = 12
export const DRAG = 22
export const GRAZE_RATE = 0.02
export const GRAZE_GAIN = 1.8
export const ANG_DRAG = 12
export const CHEMO_ACCEL = 3.5
export const MAX_ACCEL = 1.2
export const COLLISION_KICK = 0.5
export const MAX_SPIN = 2.0
export const PEAK_MIN = 0.18
export const SENSE_BOOST = 0.25
