export const SPHERE_RADIUS = 5
export const SURFACE = SPHERE_RADIUS + 0.06
export const CELL_COUNT = 120
export const MAX_CELLS = 500
export const FOOD_COUNT = 7000
export const GRID = 0.35
export const CELL_GRID = 1.0
export const SPRING = 22
export const FIXED_DT = 1 / 60
export const MAX_STEPS = 200

export const MIN_RADIUS = 0.10
export const MAX_RADIUS = 0.37
export const START_RADIUS = 0.13
export const GROWTH_PER_FOOD = 0.0005
export const ABSORB_CAP = 3
export const MITO_TIME = 90
export const MITO_HOLD = 0.2
export const MITO_FADE = 0.4
export const MITO_NEAR = 2.1
export const MITO_SEP = 2.8
export const MITO_SLOW_FRAC = 0.6
export const MITO_REST = 4

export const WIDTH = 0.085
export const TAIL_SEGMENTS = 8
export const TAIL_LINK = 0.11
export const TAIL_LINK_FILL = 0.9
export const TAIL_BASE_RATE = 1.6
export const TAIL_JOINT_RATE = 2.0
export const TAIL_OSC_FREQ = 7
export const TAIL_OSC_AMP = 0.5
export const TAIL_OSC_WAVE = 0.9
export const THRUST = 12
export const DRAG = 22
export const GRAZE_RATE = 0.01
export const GRAZE_GAIN = 6.0
export const ANG_DRAG = 12
export const CHEMO_ACCEL = 3.5
export const MAX_ACCEL = 1.2
export const COLLISION_KICK = 0.5
export const MAX_SPIN = 2.0
export const PEAK_MIN = 0.18
export const SENSE_BOOST = 0.25
export const SENSE_PERIOD = 0.05
export const CULL_COS = -0.06
